In [1]:
# !pip install torch
# !pip install transformers

In [2]:
# Regular imports
import matplotlib.pyplot as plt
import torch

from torch import nn
import numpy as np 


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device




'cuda'

In [4]:
data_path = "/kaggle/input/majortry6/labeled_data.csv"

In [5]:
import numpy as np
import pickle
import pandas as pd
pd.options.mode.copy_on_write = True

data = pd.read_csv(data_path)
df = pd.DataFrame(data)
print(df.columns)
df.columns = ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'classk', 'tweet']

Index(['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'class', 'tweet'],
      dtype='object')


In [6]:
df["classk"] = df["classk"].map({2:1, 1:0, 0:0}) 
# label = 0 = hate
# label = 1 = not_hate

In [7]:
tweets = df.tweet
res = []

for i in range(len(tweets)):
    splitt = tweets[i].split(":")
    if len(splitt) == 1:
        res.append(splitt[0])
    else:
        res.append(splitt[-1])
        
tweets = res

# print(tweets)

In [8]:
hate_words = ['Moist', 'Cunt', 'Panties', 'Fuck', 'Hate', 'Nigger', 'Pussy', 'Ass', 'Motherfucker', 'Bitch', 'Damn']
not_hate_words = ['Love', 'Peace', 'Kindness', 'Happiness', 'Respect', 'Friendship',
'Appreciation', 'Hope', 'Encouragement', 'Support', 'Caring']

In [9]:
from transformers import AutoTokenizer
from transformers import BertModel

# Load pre-trained RoBERTa model and tokenizer
model_name = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name, token="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")

tokenizer("I love Pokemon")



tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

{'input_ids': [101, 1045, 2293, 20421, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [10]:
model =  BertModel.from_pretrained(model_name)

inputs = tokenizer("Hello my dog is cute", return_tensors="pt")
print(inputs)

outputs = model(**inputs)

print(len(outputs.last_hidden_state[0])) # => no. of tokens + [CLS] + [SEP]
print(len(outputs.last_hidden_state[0][1])) # => hidden dim size
print(len(outputs.last_hidden_state[0][2])) # => hidden dim size

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

{'input_ids': tensor([[  101,  7592,  2026,  3899,  2003, 10140,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
7
768
768


In [11]:
inputs = tokenizer("shatterd", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[ 0.2913,  0.1975, -0.5855,  ..., -0.4437,  0.1399, -0.9847],
        [-0.1661, -0.3250, -0.5277,  ..., -0.0728,  0.1911, -0.3950],
        [ 0.7250,  0.1073, -0.4565,  ...,  0.0299, -0.7225, -0.3065]],
       grad_fn=<SliceBackward0>)


In [12]:
inputs = tokenizer("shatter", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[ 0.2042, -0.1103, -0.0437,  ...,  0.0647,  0.0985, -0.7743],
        [ 0.8504,  0.1411, -0.2318,  ..., -0.1123, -0.8131, -0.2168]],
       grad_fn=<SliceBackward0>)


In [13]:
temp = []
# model = BertModel.from_pretrained("bert-base-uncased")

for word in hate_words:
    inputs = tokenizer(word, return_tensors="pt")
#     print(inputs)
    outputs = model(**inputs)
    
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    """calculating mean of embeddings execept cls token
    since words may be tokinized differently like (motherF***)=>(mother,F***)
    we take average of those embeddings to represent each word """
    temp.append(outputs.tolist())


hate_space =torch.tensor(temp).to(device).requires_grad_()

hate_space.is_leaf
hate_space.dtype


torch.float32

In [14]:
hate_space.shape

torch.Size([11, 768])

In [15]:
temp = []

for word in not_hate_words:
    inputs = tokenizer(word, return_tensors="pt")

    outputs = model(**inputs)
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    temp.append(outputs.tolist())

not_hate_space = torch.tensor(temp).to(device).requires_grad_()

print(not_hate_space.is_leaf)


True


In [16]:
# Trial matmul

t1 = torch.randn(11, 768)
t2 = torch.randn(4, 23, 768)

print(torch.transpose(t2, 1, 2).shape)

torch.matmul(t1, torch.transpose(t2, 1, 2)).shape

torch.Size([4, 768, 23])


torch.Size([4, 11, 23])

In [17]:
print("hate_space.grad:", hate_space.grad)
print("not_hate_space.grad:", not_hate_space.grad)

hate_space.grad: None
not_hate_space.grad: None


In [18]:
class Custom_Dataset(torch.utils.data.Dataset):
    
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
        
    def __getitem__(self, index: int) -> (torch.Tensor, int): # => (X, y)
        
        X = self.data[index]
        y = self.labels[index]

        return (X, y)
    
    
    def __len__(self) -> int:
        
        return len(self.data)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tweets, list(df.classk), test_size=0.2, shuffle=True)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.15, shuffle=True, stratify=y_train  # 20% validation
)

print(len(X_train), len(y_train))
print(len(X_test), len(y_test))
print(len(X_val),len(y_val))

16852 16852
4957 4957
2974 2974


In [20]:
train_data = Custom_Dataset(data=X_train, labels=y_train)
test_data = Custom_Dataset(data=X_test, labels=y_test)
val_data=Custom_Dataset(data=X_val,labels=y_val)


train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=3, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_data, batch_size=1, shuffle=False)
val_loader=torch.utils.data.DataLoader(dataset=val_data, batch_size=1, shuffle=True)

In [21]:
import random
l=[[random.uniform(0,1)] for i in range(11)]
l

[[0.6453506763585883],
 [0.5605880268958852],
 [0.7658220756426797],
 [0.5988810268585553],
 [0.6850791097526624],
 [0.022568775694814747],
 [0.6563067710342315],
 [0.977839659047901],
 [0.5328126481200185],
 [0.586541731949074],
 [0.9164603963648683]]

In [22]:
# next(iter(test_loader)) 
tensor_shape = (11,1)
hate_space_weights = torch.tensor(l).to(device).requires_grad_()
not_hate_space_weights = torch.tensor(l).to(device).requires_grad_()

print(hate_space_weights.device,not_hate_space_weights.is_leaf)

cuda:0 True


In [23]:
hate_space_weights.shape

torch.Size([11, 1])

In [24]:
hate_space_weights.is_leaf

True

In [25]:
import torch.nn.functional as F

class Model0(nn.Module):

    def __init__(self, model, tokenizer):
        super().__init__()
        self.tokenizer = tokenizer
        self.model = model

    def forward(self, X):
        inputs = self.tokenizer(X, return_tensors="pt").to(device)
        outputs = self.model(**inputs)
        outputs = outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])].transpose(0, 1)#shape=>(768,no of tokens)
        col_norms = torch.norm(outputs, p=2, dim=0, keepdim=True)
        outputs = outputs / col_norms#makes every word rep unit vector 
        hate_att_scores=torch.matmul(hate_space/torch.norm(hate_space,p=2, dim=0, keepdim=True),outputs)#shape=>(11,v)
        not_hate_att_scores=torch.matmul(not_hate_space/torch.norm(not_hate_space,p=2, dim=0, keepdim=True),outputs)#shape=>(11,v)
        Psk_hate = torch.matmul(hate_att_scores.mean(1), hate_space_weights)#shape=>(1)
        Psk_not_hate = torch.matmul(not_hate_att_scores.mean(1), not_hate_space_weights)#shape=>(1)
        output_tensor = torch.cat((Psk_hate, Psk_not_hate), dim=0).requires_grad_()#
        return output_tensor


mathematically
**a.b/|a||b|=^a.^b**

**a.(b+c+d)=a.b+a.c+a.d**

In [26]:
model0 = Model0(model, tokenizer)

# X, y = next(iter(train_loader))
# Psk_hate, Psk_not_hate = model0(X)

sizes of tensors :
hate_space and not hate_space =>(11,768)



hate_space_weights and not_hate_space_weights =>(11,1)

# Semi-SSM

In [27]:
def L_inter(spaces):
    """this function calculates inter space losses between spaces 
    forces the class spaces of different class to move apart
    """
    means = [torch.mean(spaces[i]) for i in range(spaces.shape[0])]
    
    loss = torch.tensor(0.0, requires_grad=True)
    
    for k in range(len(means)):
        cur = torch.tensor(0.0, requires_grad=True)
        for l in range(len(means)):
            if l == k:
                continue
            cur = cur + (1 / (1 - ((means[k] * means[l]))))
        
        loss = loss + cur
    
    return loss
            
            

def L_intra(spaces):
    """"this function calculates intra space loss 
forces the vector representations inside a class space to have high variability(varience)
"""
    loss=torch.tensor(0.0, requires_grad=True)
    for k in range(len(spaces)):
        loss=loss+1/torch.var(spaces[k], dim=0)
    
    return torch.sum(loss)/loss.shape[0]




In [28]:
L_inter(torch.concat((torch.tensor([[0.33, 0.54, 0.37], [0.72, 0.74, 0.31], [0.61, 0.26, 0.56]], dtype=torch.float32), 
       torch.tensor([[0.22, 0.32, 0.15], [0.12, -0.08, 0.45], [0.14, 0.28, -0.11]], dtype=torch.float32))))

tensor(33.6994, grad_fn=<AddBackward0>)

In [29]:
print(hate_space,not_hate_space)

tensor([[ 0.8009,  0.2601,  0.2316,  ...,  0.0455,  0.0118, -0.0370],
        [ 0.1845, -0.0866,  0.1542,  ..., -0.2302, -0.3558, -0.2348],
        [ 0.6341,  0.0180, -0.3330,  ...,  0.1851, -0.3067, -0.4023],
        ...,
        [ 0.8014,  0.2637,  0.2895,  ...,  0.1221,  0.1728, -0.4732],
        [ 0.5409,  0.4092, -0.2325,  ...,  0.1790, -0.2709, -0.0346],
        [ 0.5508,  0.1983,  0.0521,  ...,  0.3905, -0.0753, -0.5880]],
       device='cuda:0', requires_grad=True) tensor([[ 0.5933,  0.2685, -0.0267,  ..., -0.4845, -0.4192, -0.3698],
        [ 0.2493,  0.1343, -0.1606,  ..., -0.1305, -0.3765, -0.3898],
        [ 0.0551, -0.1996, -0.1785,  ..., -0.0520, -0.1908, -0.2057],
        ...,
        [ 0.2502, -0.2729, -0.2597,  ...,  0.1696, -0.5105, -0.0785],
        [ 0.2900, -0.2058, -0.1541,  ..., -0.0185, -0.5686,  0.0864],
        [ 0.2823, -0.0846, -0.1393,  ...,  0.1534, -0.2074, -0.2804]],
       device='cuda:0', requires_grad=True)


In [30]:
print(hate_space_weights,not_hate_space_weights)

tensor([[0.6454],
        [0.5606],
        [0.7658],
        [0.5989],
        [0.6851],
        [0.0226],
        [0.6563],
        [0.9778],
        [0.5328],
        [0.5865],
        [0.9165]], device='cuda:0', requires_grad=True) tensor([[0.6454],
        [0.5606],
        [0.7658],
        [0.5989],
        [0.6851],
        [0.0226],
        [0.6563],
        [0.9778],
        [0.5328],
        [0.5865],
        [0.9165]], device='cuda:0', requires_grad=True)


In [31]:
model0.to(device)

print(hate_space.is_leaf)
optimizer = torch.optim.Adam(params=[hate_space, not_hate_space, hate_space_weights, not_hate_space_weights], lr=0.0002)
model0.train()

model0.train()

curr=0.1
prev=0
pprev=0
while curr>=prev:
    for i, batch in enumerate(train_loader):
#         if i == 1:
#             break
        if i % 2000 == 0:
            print(i)

        x, Y = batch
        loss = 0

        for X, y in zip(x, Y):
            y_preds = model0(X)
#             print(y_preds)
            #print(f"printing y_preds={y_preds} shape={y_preds.shape}")

            loss+=F.cross_entropy(y_preds.view(1, -1).to(device), torch.tensor([y]).to(device))
            """explisit soft max is not used to convert to probs is cross 
            entrophy loss has inbuilt softmax  function adding softmax explisity
            will effect adversly by smoothing again on smoothed values will decrese 
            the weightage for class with high prob """
#             break
        loss /= len(x)
        loss += 1*L_inter(torch.cat((hate_space, not_hate_space))) + 1*L_intra(torch.stack([hate_space, not_hate_space]))
            
        optimizer.zero_grad()
        
        loss.backward()
        optimizer.step()
    correct = 0
    total = len(y_val)

    true = []
    preds = []

    with torch.inference_mode():
        for i, batch in enumerate(val_loader):

            X, y = batch
            Psk_hate, Psk_not_hate = model0(X)

            y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

            true.extend(y)
            preds.append(y_predict)

            cur = torch.eq(y_predict, y)

            correct += torch.sum(cur)
    pprev=prev
    prev=curr
    print(f"Test Accuracy: {correct/total}")
    curr=correct/total
  





True
0
2000
4000
Test Accuracy: 0.8312037587165833
0
2000
4000
Test Accuracy: 0.8342300057411194
0
2000
4000
Test Accuracy: 0.8466711640357971
0
2000
4000
Test Accuracy: 0.8560860753059387
0
2000
4000
Test Accuracy: 0.8618022799491882
0
2000
4000
Test Accuracy: 0.862474799156189
0
2000
4000
Test Accuracy: 0.8611298203468323


In [32]:
print(hate_space_weights.shape,not_hate_space_weights.shape)

torch.Size([11, 1]) torch.Size([11, 1])


In [33]:
print(hate_space,not_hate_space)

tensor([[ 1.9451,  1.5622,  4.3646,  ..., -1.8549,  0.8603,  0.9552],
        [-0.8580, -1.2810,  1.6500,  ..., -1.8777, -2.3636,  0.7452],
        [ 2.1083, -1.1370, -1.1349,  ...,  0.7400, -2.2220, -1.9243],
        ...,
        [ 1.6200,  1.3377,  3.0023,  ...,  0.8588,  0.9971, -2.0534],
        [-0.8535,  1.7556, -1.0400,  ...,  0.9295, -2.4159,  0.9346],
        [ 2.2136,  1.3302,  0.8934,  ...,  0.7063,  0.5021, -1.6501]],
       device='cuda:0', requires_grad=True) tensor([[ 2.3213,  1.6527,  0.4195,  ..., -1.3256, -2.8525, -2.8659],
        [-1.4909,  2.1032,  1.0010,  ..., -1.4760, -6.8403, -5.5976],
        [-1.0948, -1.8241,  0.8878,  ...,  2.1954,  1.7476,  1.1275],
        ...,
        [-1.2478, -2.0203, -2.1122,  ...,  2.4278, -0.9064,  1.1770],
        [-1.2856, -1.9381,  0.6654,  ...,  2.6401, -0.9336,  1.1646],
        [-0.3634, -1.5526,  0.2280,  ...,  1.6730,  1.7375, -1.9960]],
       device='cuda:0', requires_grad=True)


In [34]:
hate_space_weights

tensor([[0.8728],
        [1.0845],
        [1.0087],
        [1.0012],
        [0.8887],
        [0.1314],
        [0.8010],
        [1.4668],
        [0.9350],
        [0.9497],
        [1.2665]], device='cuda:0', requires_grad=True)

In [35]:
torch.concat((hate_space, not_hate_space)).shape

torch.Size([22, 768])

In [36]:
correct = 0
total = len(y_test)

true = []
preds = []

with torch.inference_mode():
    for i, batch in enumerate(test_loader):

        X, y = batch
        Psk_hate, Psk_not_hate = model0(X)

        y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

        true.extend(y)
        preds.append(y_predict)

        cur = torch.eq(y_predict, y)

        correct += torch.sum(cur)

print(f"Test Accuracy: {correct/total}")
print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / total}")       

Test Accuracy: 0.8648375868797302
Test Accuracy: 0.8648375868797302


In [37]:
from sklearn.metrics import precision_score, recall_score

print(precision_score(y_test, preds, average='macro'))
print(recall_score(y_test, preds, average='macro'))

0.8022750382589237
0.6238589104960208


In [38]:
import torch.nn.functional as F
import torch

# Corrected target with integer values
target = torch.tensor([0])

# Providing float values for input, as cross_entropy expects logits
input_values = torch.tensor([1.0, 0.0])

# Calculate cross-entropy loss
F.cross_entropy(input_values.unsqueeze(0), target)

tensor(0.3133)