In [37]:
# !pip install torch
# !pip install transformers

In [38]:
# Regular imports
import matplotlib.pyplot as plt
import torch

from torch import nn
import numpy as np 


In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device




'cuda'

In [40]:
data_path = "/kaggle/input/majortry6/labeled_data.csv"

In [41]:
import numpy as np
import pickle
import pandas as pd
pd.options.mode.copy_on_write = True

data = pd.read_csv(data_path)
df = pd.DataFrame(data)
print(df.columns)
df.columns = ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'classk', 'tweet']

Index(['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'class', 'tweet'],
      dtype='object')


In [42]:
df["classk"] = df["classk"].map({2:1, 1:0, 0:0}) 
# label = 0 = hate
# label = 1 = not_hate

In [43]:
tweets = df.tweet
res = []

for i in range(len(tweets)):
    splitt = tweets[i].split(":")
    if len(splitt) == 1:
        res.append(splitt[0])
    else:
        res.append(splitt[-1])
        
tweets = res

# print(tweets)

In [44]:
hate_words = ['Moist', 'Cunt', 'Panties', 'Fuck', 'Hate', 'Nigger', 'Pussy', 'Ass', 'Motherfucker', 'Bitch', 'Damn']
not_hate_words = ['Love', 'Peace', 'Kindness', 'Happiness', 'Respect', 'Friendship',
'Appreciation', 'Hope', 'Encouragement', 'Support', 'Caring']

In [45]:
from transformers import RobertaModel, RobertaTokenizer

# Load pre-trained RoBERTa model and tokenizer
model_name = "roberta-base"

tokenizer = RobertaTokenizer.from_pretrained(model_name, token="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")

tokenizer("I love Pokemon")



{'input_ids': [0, 100, 657, 26052, 2], 'attention_mask': [1, 1, 1, 1, 1]}

In [46]:
model =  RobertaModel.from_pretrained(model_name)

inputs = tokenizer("Hello my dog is cute", return_tensors="pt")
print(inputs)

outputs = model(**inputs)

print(len(outputs.last_hidden_state[0])) # => no. of tokens + [CLS] + [SEP]
print(len(outputs.last_hidden_state[0][1])) # => hidden dim size
print(len(outputs.last_hidden_state[0][2])) # => hidden dim size

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[    0, 31414,   127,  2335,    16, 11962,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
7
768
768


In [47]:
inputs = tokenizer("shatterd", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[-0.1097, -0.0864,  0.1443,  ..., -0.3975,  0.1201, -0.0709],
        [ 0.1166, -0.1417, -0.0394,  ..., -0.3211, -0.1199, -0.1773],
        [ 0.1630, -0.1101,  0.0422,  ..., -0.0305,  0.0285, -0.0697],
        [-0.0517,  0.0818, -0.0415,  ..., -0.1247, -0.0896, -0.0421]],
       grad_fn=<SliceBackward0>)


In [48]:
inputs = tokenizer("shatter", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[-0.0217, -0.0436,  0.0626,  ..., -0.1816,  0.0255,  0.2100],
        [ 0.0523,  0.1572, -0.0863,  ..., -0.3361, -0.0153,  0.1608],
        [-0.0574,  0.0975, -0.0369,  ..., -0.1255, -0.0795, -0.0347]],
       grad_fn=<SliceBackward0>)


In [49]:
temp = []
# model = BertModel.from_pretrained("bert-base-uncased")

for word in hate_words:
    inputs = tokenizer(word, return_tensors="pt")
#     print(inputs)
    outputs = model(**inputs)
    
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    """calculating mean of embeddings execept cls token
    since words may be tokinized differently like (motherF***)=>(mother,F***)
    we take average of those embeddings to represent each word """
    temp.append(outputs.tolist())


hate_space =torch.tensor(temp).to(device).requires_grad_()

hate_space.is_leaf
hate_space.dtype


torch.float32

In [50]:
hate_space.shape

torch.Size([11, 768])

In [51]:
temp = []

for word in not_hate_words:
    inputs = tokenizer(word, return_tensors="pt")

    outputs = model(**inputs)
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    temp.append(outputs.tolist())

not_hate_space = torch.tensor(temp).to(device).requires_grad_()

print(not_hate_space.is_leaf)


True


In [52]:
# Trial matmul

t1 = torch.randn(11, 768)
t2 = torch.randn(4, 23, 768)

print(torch.transpose(t2, 1, 2).shape)

torch.matmul(t1, torch.transpose(t2, 1, 2)).shape

torch.Size([4, 768, 23])


torch.Size([4, 11, 23])

In [53]:
print("hate_space.grad:", hate_space.grad)
print("not_hate_space.grad:", not_hate_space.grad)

hate_space.grad: None
not_hate_space.grad: None


In [54]:
class Custom_Dataset(torch.utils.data.Dataset):
    
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
        
    def __getitem__(self, index: int) -> (torch.Tensor, int): # => (X, y)
        
        X = self.data[index]
        y = self.labels[index]

        return (X, y)
    
    
    def __len__(self) -> int:
        
        return len(self.data)

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tweets, list(df.classk), test_size=0.2, shuffle=True)

print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

19826 19826
4957 4957


In [56]:
train_data = Custom_Dataset(data=X_train, labels=y_train)
test_data = Custom_Dataset(data=X_test, labels=y_test)

train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=3, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_data, batch_size=1, shuffle=False)


In [57]:
import random
l=[[random.uniform(-1,1)] for i in range(11)]
l

[[-0.9730272007670802],
 [0.8358091393459206],
 [-0.14008327768198559],
 [0.8846264231614258],
 [0.5164325705426474],
 [-0.3419881549537507],
 [-0.49921674328742127],
 [-0.047478615764504184],
 [-0.42660397772583236],
 [-0.37187613158194877],
 [-0.6439363544080858]]

In [58]:
# next(iter(test_loader)) 
tensor_shape = (11,1)
hate_space_weights = torch.tensor(l).to(device).requires_grad_()
not_hate_space_weights = torch.tensor(l).to(device).requires_grad_()

print(hate_space_weights.device,not_hate_space_weights.is_leaf)

cuda:0 True


In [59]:
hate_space_weights.shape

torch.Size([11, 1])

In [60]:
hate_space_weights.is_leaf

True

In [61]:
import torch.nn.functional as F

class Model0(nn.Module):

    def __init__(self, model, tokenizer):
        super().__init__()
        self.tokenizer = tokenizer
        self.model = model

    def forward(self, X):
        inputs = self.tokenizer(X, return_tensors="pt").to(device)
        outputs = self.model(**inputs)
        outputs = outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])].transpose(0, 1)
        print("outputes from bert model",outputs.shape)
        col_norms = torch.norm(outputs, p=2, dim=0, keepdim=True)
        outputs = outputs / col_norms
        """taking norms early because if we take norms and divide each vector 
        with norm we get unit vectors without altreing direction which will be 
        same as dividing with norms after multiplication 
        similarly for hate and not_hate space.
        indeed it doesnt alter results of model it just simplifies the model """
#         print("outputes from bert model",outputs.shape)
        hate_att_scores=torch.matmul(hate_space/torch.norm(hate_space,p=2, dim=0, keepdim=True),outputs)
        not_hate_att_scores=torch.matmul(not_hate_space/torch.norm(not_hate_space,p=2, dim=0, keepdim=True),outputs)
#         print(hate_att_scores.mean(1).shape)
        Psk_hate = torch.matmul(hate_att_scores.mean(1), hate_space_weights)
        Psk_not_hate = torch.matmul(not_hate_att_scores.mean(1), not_hate_space_weights)
#         print(f"printing Psk_hate={Psk_hate} shape={Psk_hate.shape} and Psk_not_hate={Psk_not_hate} shape={Psk_not_hate.shape}")
        
        output_tensor = torch.cat((Psk_hate, Psk_not_hate), dim=0).requires_grad_()

        return output_tensor


mathematically
**a.b/|a||b|=^a.^b**

**a.(b+c+d)=a.b+a.c+a.d**

In [62]:
model0 = Model0(model, tokenizer)

# X, y = next(iter(train_loader))
# Psk_hate, Psk_not_hate = model0(X)

# Semi-SSM

In [63]:
def L_inter(spaces):
    """this function calculates inter space losses between spaces 
    forces the class spaces of different class to move apart
    """
    means = [torch.mean(spaces[i]) for i in range(spaces.shape[0])]
    
    loss = torch.tensor(0.0, requires_grad=True)
    
    for k in range(len(means)):
        cur = torch.tensor(0.0, requires_grad=True)
        for l in range(len(means)):
            if l == k:
                continue
            cur = cur + (1 / (1 - ((means[k] * means[l]))))
        
        loss = loss + cur
    
    return loss
            
            

def L_intra(spaces):
    """"this function calculates intra space loss 
forces the vector representations inside a class space to have high variability(varience)
"""
    loss=torch.tensor(0.0, requires_grad=True)
    for k in range(len(spaces)):
        loss=loss+1/torch.var(spaces[k], dim=0)
    
    return torch.sum(loss)/loss.shape[0]




In [64]:
L_inter(torch.concat((torch.tensor([[0.33, 0.54, 0.37], [0.72, 0.74, 0.31], [0.61, 0.26, 0.56]], dtype=torch.float32), 
       torch.tensor([[0.22, 0.32, 0.15], [0.12, -0.08, 0.45], [0.14, 0.28, -0.11]], dtype=torch.float32))))

tensor(33.6994, grad_fn=<AddBackward0>)

In [65]:
print(hate_space,not_hate_space)

tensor([[-0.0310,  0.1629,  0.0097,  ..., -0.0019,  0.0305, -0.0738],
        [-0.0411,  0.0255, -0.0069,  ..., -0.3014, -0.0704, -0.0058],
        [ 0.0085,  0.0397,  0.0388,  ..., -0.1430,  0.0385,  0.0430],
        ...,
        [-0.1312, -0.0045, -0.0484,  ..., -0.2071, -0.0556, -0.0245],
        [-0.0346,  0.1688,  0.0396,  ..., -0.2303, -0.1220,  0.0037],
        [-0.0049,  0.0358,  0.0281,  ..., -0.1855, -0.0979, -0.0800]],
       device='cuda:0', requires_grad=True) tensor([[-0.0039,  0.0822,  0.0470,  ..., -0.0254, -0.0671, -0.0814],
        [ 0.0216,  0.1387,  0.0708,  ..., -0.1220, -0.0591, -0.0006],
        [-0.1839,  0.1045,  0.1317,  ...,  0.1253, -0.0803,  0.0557],
        ...,
        [-0.0444,  0.0534,  0.0910,  ...,  0.1400,  0.0228, -0.0028],
        [-0.1128,  0.0228,  0.0920,  ...,  0.0764, -0.0988,  0.0147],
        [-0.0823,  0.0630,  0.0675,  ..., -0.0101, -0.0605,  0.0270]],
       device='cuda:0', requires_grad=True)


In [66]:
print(hate_space_weights,not_hate_space_weights)

tensor([[-0.9730],
        [ 0.8358],
        [-0.1401],
        [ 0.8846],
        [ 0.5164],
        [-0.3420],
        [-0.4992],
        [-0.0475],
        [-0.4266],
        [-0.3719],
        [-0.6439]], device='cuda:0', requires_grad=True) tensor([[-0.9730],
        [ 0.8358],
        [-0.1401],
        [ 0.8846],
        [ 0.5164],
        [-0.3420],
        [-0.4992],
        [-0.0475],
        [-0.4266],
        [-0.3719],
        [-0.6439]], device='cuda:0', requires_grad=True)


In [67]:
model0.to(device)

print(hate_space.is_leaf)
optimizer = torch.optim.Adam(params=[hate_space, not_hate_space, hate_space_weights, not_hate_space_weights], lr=0.01)
model0.train()

model0.train()

cur=0.1
prev=0
pprev=0
for _ in range(3) :
    for i, batch in enumerate(train_loader):
#         if i == 1:
#             break
        if i % 2000 == 0:
            print(i)

        x, Y = batch
        loss = 0

        for X, y in zip(x, Y):
            y_preds = model0(X)
#             print(y_preds)
            print(f"printing y_preds={y_preds} shape={y_preds.shape}")

            loss+=F.cross_entropy(y_preds.view(1, -1).to(device), torch.tensor([y]).to(device))
            """explisit soft max is not used to convert to probs is cross 
            entrophy loss has inbuilt softmax  function adding softmax explisity
            will effect adversly by smoothing again on smoothed values will decrese 
            the weightage for class with high prob """
#             break
        loss /= len(x)
        loss += 1*L_inter(torch.cat((hate_space, not_hate_space))) + 1*L_intra(torch.stack([hate_space, not_hate_space]))
            
        optimizer.zero_grad()
        
        loss.backward()
        optimizer.step()





True
0
outputes from bert model torch.Size([768, 36])
outputes from bert model torch.Size([768, 36])
torch.Size([11])
printing Psk_hate=tensor([-0.8119], device='cuda:0', grad_fn=<SqueezeBackward4>) shape=torch.Size([1]) and Psk_not_hate=tensor([-0.6058], device='cuda:0', grad_fn=<SqueezeBackward4>) shape=torch.Size([1])
printing y_preds=tensor([-0.8119, -0.6058], device='cuda:0', grad_fn=<CatBackward0>) shape=torch.Size([2])
outputes from bert model torch.Size([768, 12])
outputes from bert model torch.Size([768, 12])
torch.Size([11])
printing Psk_hate=tensor([-1.1301], device='cuda:0', grad_fn=<SqueezeBackward4>) shape=torch.Size([1]) and Psk_not_hate=tensor([-0.7485], device='cuda:0', grad_fn=<SqueezeBackward4>) shape=torch.Size([1])
printing y_preds=tensor([-1.1301, -0.7485], device='cuda:0', grad_fn=<CatBackward0>) shape=torch.Size([2])
outputes from bert model torch.Size([768, 28])
outputes from bert model torch.Size([768, 28])
torch.Size([11])
printing Psk_hate=tensor([-0.9262], 


KeyboardInterrupt



In [ ]:
print(hate_space_weights.shape,not_hate_space_weights.shape)

In [ ]:
print(hate_space,not_hate_space)

In [ ]:
hate_space_weights

In [ ]:
torch.concat((hate_space, not_hate_space)).shape

In [ ]:
correct = 0
total = len(y_test)

true = []
preds = []

with torch.inference_mode():
    for i, batch in enumerate(test_loader):
        if i < 1000 == 0:
            continue
        X, y = batch
        Psk_hate, Psk_not_hate = model0(X)

        y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

        true.extend(y)
        preds.append(y_predict)

        cur = torch.eq(y_predict, y)

        correct += torch.sum(cur)

print(f"Test Accuracy: {correct/total}")
print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / total}")       

In [ ]:
from sklearn.metrics import precision_score, recall_score

print(precision_score(y_test, preds, average='macro'))
print(recall_score(y_test, preds, average='macro'))

In [ ]:
np.save("/kaggle/working/weights.txt", [hate_space,not_hate_space,hate_space_weights,not_hate_space_weights])