In [1]:
# !pip install torch
# !pip install transformers

In [2]:
# Regular imports
import matplotlib.pyplot as plt
import torch

from torch import nn
import numpy as np 


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device




'cuda'

In [4]:
data_path = "/kaggle/input/majortry6/labeled_data.csv"

In [5]:
import numpy as np
import pickle
import pandas as pd
pd.options.mode.copy_on_write = True

data = pd.read_csv(data_path)
df = pd.DataFrame(data)
print(df.columns)
df.columns = ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'classk', 'tweet']

Index(['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'class', 'tweet'],
      dtype='object')


In [6]:
df["classk"] = df["classk"].map({2:1, 1:0, 0:0}) 
# label = 0 = hate
# label = 1 = not_hate

In [7]:
tweets = df.tweet
res = []

for i in range(len(tweets)):
    splitt = tweets[i].split(":")
    if len(splitt) == 1:
        res.append(splitt[0])
    else:
        res.append(splitt[-1])
        
tweets = res

# print(tweets)

In [8]:
hate_words = ['Moist', 'Cunt', 'Panties', 'Fuck', 'Hate', 'Nigger', 'Pussy', 'Ass', 'Motherfucker', 'Bitch', 'Damn']
not_hate_words = ['Love', 'Peace', 'Kindness', 'Happiness', 'Respect', 'Friendship',
'Appreciation', 'Hope', 'Encouragement', 'Support', 'Caring']

In [9]:
from transformers import RobertaModel, RobertaTokenizer

# Load pre-trained RoBERTa model and tokenizer
model_name = "mrm8488/distilroberta-finetuned-tweets-hate-speech"

tokenizer = RobertaTokenizer.from_pretrained(model_name, token="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")

tokenizer("I love Pokemon")



tokenizer_config.json:   0%|          | 0.00/261 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/713 [00:00<?, ?B/s]

{'input_ids': [0, 100, 657, 26052, 2], 'attention_mask': [1, 1, 1, 1, 1]}

In [10]:
model =  RobertaModel.from_pretrained(model_name)

inputs = tokenizer("Hello my dog is cute", return_tensors="pt")
print(inputs)

outputs = model(**inputs)

print(len(outputs.last_hidden_state[0])) # => no. of tokens + [CLS] + [SEP]
print(len(outputs.last_hidden_state[0][1])) # => hidden dim size
print(len(outputs.last_hidden_state[0][2])) # => hidden dim size

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of RobertaModel were not initialized from the model checkpoint at mrm8488/distilroberta-finetuned-tweets-hate-speech and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[    0, 31414,   127,  2335,    16, 11962,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
7
768
768


In [11]:
inputs = tokenizer("shatterd", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[-0.3945,  0.1072,  0.1669,  ..., -0.8544, -0.0269,  0.0504],
        [-0.3773,  0.0975, -0.0646,  ..., -0.7474, -0.0179,  0.2738],
        [-0.1697, -0.2861,  0.1177,  ..., -0.0455, -0.3950, -0.5112],
        [-0.2382,  0.2930, -0.0137,  ..., -0.3102,  0.0108, -0.2823]],
       grad_fn=<SliceBackward0>)


In [12]:
inputs = tokenizer("shatter", return_tensors="pt")
outputs = model(**inputs)
print(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])])

tensor([[ 0.3043,  0.4416,  0.0462,  ..., -0.5405, -0.1106, -0.0180],
        [ 0.3696,  0.4148, -0.3709,  ..., -0.5385, -0.2258, -0.0165],
        [ 0.1813,  0.4032, -0.3864,  ..., -0.1120, -0.2064, -0.5700]],
       grad_fn=<SliceBackward0>)


In [13]:
temp = []
# model = BertModel.from_pretrained("bert-base-uncased")

for word in hate_words:
    inputs = tokenizer(word, return_tensors="pt")
#     print(inputs)
    outputs = model(**inputs)
    
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    """calculating mean of embeddings execept cls token
    since words may be tokinized differently like (motherF***)=>(mother,F***)
    we take average of those embeddings to represent each word """
    temp.append(outputs.tolist())


hate_space =torch.tensor(temp).to(device).requires_grad_()

hate_space.is_leaf
hate_space.dtype


torch.float32

In [14]:
hate_space.shape

torch.Size([11, 768])

In [15]:
temp = []

for word in not_hate_words:
    inputs = tokenizer(word, return_tensors="pt")

    outputs = model(**inputs)
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    temp.append(outputs.tolist())

not_hate_space = torch.tensor(temp).to(device).requires_grad_()

print(not_hate_space.is_leaf)


True


In [16]:
# Trial matmul

t1 = torch.randn(11, 768)
t2 = torch.randn(4, 23, 768)

print(torch.transpose(t2, 1, 2).shape)

torch.matmul(t1, torch.transpose(t2, 1, 2)).shape

torch.Size([4, 768, 23])


torch.Size([4, 11, 23])

In [17]:
print("hate_space.grad:", hate_space.grad)
print("not_hate_space.grad:", not_hate_space.grad)

hate_space.grad: None
not_hate_space.grad: None


In [18]:
class Custom_Dataset(torch.utils.data.Dataset):
    
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
        
    def __getitem__(self, index: int) -> (torch.Tensor, int): # => (X, y)
        
        X = self.data[index]
        y = self.labels[index]

        return (X, y)
    
    
    def __len__(self) -> int:
        
        return len(self.data)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tweets, list(df.classk), test_size=0.2, shuffle=True)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.15, shuffle=True, stratify=y_train  # 20% validation
)

print(len(X_train), len(y_train))
print(len(X_test), len(y_test))
print(len(X_val),len(y_val))

16852 16852
4957 4957
2974 2974


In [20]:
train_data = Custom_Dataset(data=X_train, labels=y_train)
test_data = Custom_Dataset(data=X_test, labels=y_test)
val_data=Custom_Dataset(data=X_val,labels=y_val)


train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=3, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_data, batch_size=1, shuffle=False)
val_loader=torch.utils.data.DataLoader(dataset=val_data, batch_size=1, shuffle=True)

In [21]:
import random
l=[[random.uniform(0,1)] for i in range(11)]
l

[[0.7603050263935627],
 [0.3224759270315465],
 [0.6599861744873884],
 [0.6586122626261499],
 [0.8545166862525512],
 [0.32713450582996384],
 [0.7253064005316452],
 [0.4148715596601005],
 [0.9038831997346275],
 [0.3262409305209798],
 [0.5009444091772509]]

In [22]:
# next(iter(test_loader)) 
tensor_shape = (11,1)
hate_space_weights = torch.tensor(l).to(device).requires_grad_()
not_hate_space_weights = torch.tensor(l).to(device).requires_grad_()

print(hate_space_weights.device,not_hate_space_weights.is_leaf)

cuda:0 True


In [23]:
hate_space_weights.shape

torch.Size([11, 1])

In [24]:
hate_space_weights.is_leaf

True

In [25]:
import torch.nn.functional as F

class Model0(nn.Module):

    def __init__(self, model, tokenizer):
        super().__init__()
        self.tokenizer = tokenizer
        self.model = model

    def forward(self, X):
        inputs = self.tokenizer(X, return_tensors="pt").to(device)
        outputs = self.model(**inputs)
        outputs = outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])].transpose(0, 1)#shape=>(768,no of tokens)
        col_norms = torch.norm(outputs, p=2, dim=0, keepdim=True)
        outputs = outputs / col_norms#makes every word rep unit vector 
        hate_att_scores=torch.matmul(hate_space/torch.norm(hate_space,p=2, dim=0, keepdim=True),outputs)#shape=>(11,v)
        not_hate_att_scores=torch.matmul(not_hate_space/torch.norm(not_hate_space,p=2, dim=0, keepdim=True),outputs)#shape=>(11,v)
        Psk_hate = torch.matmul(hate_att_scores.mean(1), hate_space_weights)#shape=>(1)
        Psk_not_hate = torch.matmul(not_hate_att_scores.mean(1), not_hate_space_weights)#shape=>(1)
        output_tensor = torch.cat((Psk_hate, Psk_not_hate), dim=0).requires_grad_()#
        return output_tensor


mathematically
**a.b/|a||b|=^a.^b**

**a.(b+c+d)=a.b+a.c+a.d**

In [26]:
model0 = Model0(model, tokenizer)

# X, y = next(iter(train_loader))
# Psk_hate, Psk_not_hate = model0(X)

sizes of tensors :
hate_space and not hate_space =>(11,768)



hate_space_weights and not_hate_space_weights =>(11,1)

# Semi-SSM

In [27]:
def L_inter(spaces):
    """this function calculates inter space losses between spaces 
    forces the class spaces of different class to move apart
    """
    means = [torch.mean(spaces[i]) for i in range(spaces.shape[0])]
    
    loss = torch.tensor(0.0, requires_grad=True)
    
    for k in range(len(means)):
        cur = torch.tensor(0.0, requires_grad=True)
        for l in range(len(means)):
            if l == k:
                continue
            cur = cur + (1 / (1 - ((means[k] * means[l]))))
        
        loss = loss + cur
    
    return loss
            
            

def L_intra(spaces):
    """"this function calculates intra space loss 
forces the vector representations inside a class space to have high variability(varience)
"""
    loss=torch.tensor(0.0, requires_grad=True)
    for k in range(len(spaces)):
        loss=loss+1/torch.var(spaces[k], dim=0)
    
    return torch.sum(loss)/loss.shape[0]




In [28]:
L_inter(torch.concat((torch.tensor([[0.33, 0.54, 0.37], [0.72, 0.74, 0.31], [0.61, 0.26, 0.56]], dtype=torch.float32), 
       torch.tensor([[0.22, 0.32, 0.15], [0.12, -0.08, 0.45], [0.14, 0.28, -0.11]], dtype=torch.float32))))

tensor(33.6994, grad_fn=<AddBackward0>)

In [29]:
print(hate_space,not_hate_space)

tensor([[-0.3241,  0.4376, -0.1251,  ..., -0.0201,  0.1048, -0.1907],
        [-0.5006,  0.4816, -0.1918,  ..., -0.4411, -0.0842,  0.3000],
        [-0.3469,  0.8489,  0.2848,  ..., -0.1552,  0.3376,  0.4976],
        ...,
        [ 0.0782, -0.3213, -0.8124,  ...,  0.1717, -0.1118, -0.7043],
        [-0.1637,  0.8197, -0.0170,  ..., -0.0628,  0.0574,  0.0210],
        [ 0.2143,  0.0388, -0.1520,  ...,  0.1129, -0.0484, -0.3165]],
       device='cuda:0', requires_grad=True) tensor([[-0.5628,  0.7036,  0.1992,  ..., -0.1542, -0.2368,  0.4712],
        [-0.6843,  0.9208,  0.4360,  ..., -0.5782, -0.0209,  0.7394],
        [-0.6714,  0.8915,  0.2514,  ..., -0.3889, -0.1631,  0.5822],
        ...,
        [-0.4569,  0.6154,  0.1839,  ..., -0.2888, -0.0969,  0.5756],
        [-0.6840,  0.7483,  0.2923,  ..., -0.0196, -0.1049,  0.4473],
        [-0.2515,  0.7116, -0.1201,  ..., -0.3662, -0.0734,  0.5325]],
       device='cuda:0', requires_grad=True)


In [30]:
print(hate_space_weights,not_hate_space_weights)

tensor([[0.7603],
        [0.3225],
        [0.6600],
        [0.6586],
        [0.8545],
        [0.3271],
        [0.7253],
        [0.4149],
        [0.9039],
        [0.3262],
        [0.5009]], device='cuda:0', requires_grad=True) tensor([[0.7603],
        [0.3225],
        [0.6600],
        [0.6586],
        [0.8545],
        [0.3271],
        [0.7253],
        [0.4149],
        [0.9039],
        [0.3262],
        [0.5009]], device='cuda:0', requires_grad=True)


In [31]:
model0.to(device)

print(hate_space.is_leaf)
optimizer = torch.optim.Adam(params=[hate_space, not_hate_space, hate_space_weights, not_hate_space_weights], lr=0.00002)
model0.train()

model0.train()

cur=0.1
prev=0

while cur>prev :
    for i, batch in enumerate(train_loader):
#         if i == 1:
#             break
        if i % 2000 == 0:
            print(i)

        x, Y = batch
        loss = 0

        for X, y in zip(x, Y):
            y_preds = model0(X)
#             print(y_preds)
            #print(f"printing y_preds={y_preds} shape={y_preds.shape}")

            loss+=F.cross_entropy(y_preds.view(1, -1).to(device), torch.tensor([y]).to(device))
            """explisit soft max is not used to convert to probs is cross 
            entrophy loss has inbuilt softmax  function adding softmax explisity
            will effect adversly by smoothing again on smoothed values will decrese 
            the weightage for class with high prob """
#             break
        loss /= len(x)
        loss += 1*L_inter(torch.cat((hate_space, not_hate_space))) + 1*L_intra(torch.stack([hate_space, not_hate_space]))
            
        optimizer.zero_grad()
        
        loss.backward()
        optimizer.step()
    correct = 0
    total = len(y_val)

    true = []
    preds = []

    with torch.inference_mode():
        for i, batch in enumerate(val_loader):

            X, y = batch
            Psk_hate, Psk_not_hate = model0(X)

            y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

            true.extend(y)
            preds.append(y_predict)

            cur = torch.eq(y_predict, y)

            correct += torch.sum(cur)

    print(f"Test Accuracy: {correct/total}")
    print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / total}")  





True
0
2000
4000
Test Accuracy: 0.7074646949768066
Test Accuracy: 0.7074646949768066
0
2000
4000
Test Accuracy: 0.8096839189529419
Test Accuracy: 0.8096839189529419


In [32]:
print(hate_space_weights.shape,not_hate_space_weights.shape)

torch.Size([11, 1]) torch.Size([11, 1])


In [33]:
print(hate_space,not_hate_space)

tensor([[-0.5132,  0.5030, -0.0165,  ..., -0.1715,  0.2513, -0.1383],
        [-0.6980,  0.3156, -0.4027,  ..., -0.6305, -0.2684,  0.4471],
        [-0.5387,  1.0629,  0.4705,  ..., -0.3157,  0.5175,  0.6472],
        ...,
        [-0.0077, -0.3736, -1.0120,  ...,  0.0334, -0.1239, -0.8227],
        [-0.3612,  0.9422,  0.1708,  ..., -0.2419,  0.2230,  0.0840],
        [ 0.3741, -0.0622, -0.2134,  ..., -0.0452, -0.0222, -0.4141]],
       device='cuda:0', requires_grad=True) tensor([[-0.7832,  0.5159, -0.0034,  ...,  0.0299, -0.4088,  0.2752],
        [-0.8783,  1.1058,  0.6256,  ..., -0.7612,  0.1846,  0.9291],
        [-0.8672,  1.0809,  0.4575,  ..., -0.5857, -0.3406,  0.8035],
        ...,
        [-0.2563,  0.4357, -0.0120,  ..., -0.0937, -0.2827,  0.7881],
        [-0.8780,  0.5499,  0.4944,  ...,  0.1609, -0.2917,  0.2517],
        [-0.0607,  0.5217, -0.3061,  ..., -0.5672, -0.2688,  0.3197]],
       device='cuda:0', requires_grad=True)


In [34]:
hate_space_weights

tensor([[0.8578],
        [0.4238],
        [0.7686],
        [0.5876],
        [0.9438],
        [0.2823],
        [0.8339],
        [0.4703],
        [0.8693],
        [0.4344],
        [0.5871]], device='cuda:0', requires_grad=True)

In [35]:
torch.concat((hate_space, not_hate_space)).shape

torch.Size([22, 768])

In [36]:
correct = 0
total = len(y_test)

true = []
preds = []

with torch.inference_mode():
    for i, batch in enumerate(test_loader):

        X, y = batch
        Psk_hate, Psk_not_hate = model0(X)

        y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

        true.extend(y)
        preds.append(y_predict)

        cur = torch.eq(y_predict, y)

        correct += torch.sum(cur)

print(f"Test Accuracy: {correct/total}")
print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / total}")       

Test Accuracy: 0.8053258061408997
Test Accuracy: 0.8053258061408997


In [37]:
from sklearn.metrics import precision_score, recall_score

print(precision_score(y_test, preds, average='macro'))
print(recall_score(y_test, preds, average='macro'))

0.5666475088346083
0.5244899916152059


In [38]:
import torch.nn.functional as F
import torch

# Corrected target with integer values
target = torch.tensor([0])

# Providing float values for input, as cross_entropy expects logits
input_values = torch.tensor([1.0, 0.0])

# Calculate cross-entropy loss
F.cross_entropy(input_values.unsqueeze(0), target)

tensor(0.3133)