In [1]:
# !pip install torch
# !pip install transformers

In [2]:
# Regular imports
import matplotlib.pyplot as plt
import torch

from torch import nn
import numpy as np 


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

#os.environ['CUDA_LAUNCH_BLOCKING'] = '1'


'cuda'

In [4]:
import os
os.environ["TORCH_USE_CUDA_DSA"] = "1"

# Import PyTorch and other libraries




In [5]:
data_path = "/kaggle/input/majortry6/labeled_data.csv"

In [6]:
import numpy as np
import pickle
import pandas as pd
pd.options.mode.copy_on_write = True

data = pd.read_csv(data_path)
df = pd.DataFrame(data)
print(df.columns)
df.columns = ['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'classk', 'tweet']

Index(['Unnamed: 0', 'count', 'hate_speech', 'offensive_language', 'neither',
       'class', 'tweet'],
      dtype='object')


In [7]:
df["classk"] = df["classk"].map({2:1, 1:0, 0:0}) 
# label = 0 = hate
# label = 1 = not_hate

In [8]:
tweets = df.tweet
res = []

for i in range(len(tweets)):
    splitt = tweets[i].split(":")
    if len(splitt) == 1:
        res.append(splitt[0])
    else:
        res.append(splitt[-1])
        
tweets = res

# print(tweets)

In [9]:
hate_words = ['Moist', 'Cunt', 'Panties', 'Fuck', 'Hate', 'Nigger', 'Pussy', 'Ass', 'Motherfucker', 'Bitch', 'Damn']
not_hate_words = ['Love', 'Peace', 'Kindness', 'Happiness', 'Respect', 'Friendship',
'Appreciation', 'Hope', 'Encouragement', 'Support', 'Caring']

In [10]:
from transformers import RobertaModel, RobertaTokenizer

# Load pre-trained RoBERTa model and tokenizer
model_name = "roberta-base"

tokenizer = RobertaTokenizer.from_pretrained(model_name, token="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")

tokenizer("I love Pokemon")



tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

{'input_ids': [0, 100, 657, 26052, 2], 'attention_mask': [1, 1, 1, 1, 1]}

In [11]:
model =  RobertaModel.from_pretrained(model_name)

inputs = tokenizer("Hello my dog is cute", return_tensors="pt")
print(inputs)

outputs = model(**inputs)

print(len(outputs.last_hidden_state[0])) # => no. of tokens + [CLS] + [SEP]
print(len(outputs.last_hidden_state[0][1])) # => hidden dim size
print(len(outputs.last_hidden_state[0][2])) # => hidden dim size

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[    0, 31414,   127,  2335,    16, 11962,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
7
768
768


In [12]:
temp = []
# model = BertModel.from_pretrained("bert-base-uncased")

for word in hate_words:
    inputs = tokenizer(word, return_tensors="pt")
#     print(inputs)
    outputs = model(**inputs)
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    temp.append(outputs.tolist())

# temp = temp[1:]
# print(hate_space)
# print(len(temp)) # => no. of words = no. of rows
# print(len(temp[0])) # => no. of columns in each row = embedding vector size

# hate_space = temp.clone().detach().requires_grad_(True)
hate_space =torch.tensor(temp).to(device).requires_grad_()

hate_space.is_leaf
hate_space.dtype
# hate_space
# hate_space.requires_grad

torch.float32

In [13]:
temp = []
# model = BertModel.from_pretrained("bert-base-uncased")

# with torch.no_grad():
for word in not_hate_words:
    inputs = tokenizer(word, return_tensors="pt")
#     print(inputs)
    outputs = model(**inputs)
    outputs = torch.mean(outputs.last_hidden_state[0][1:len(outputs.last_hidden_state[0])], dim=0)
    temp.append(outputs.tolist())

# temp = temp[1:]
# print(hate_space)
# print(len(temp)) # => no. of words = no. of rows
# print(len(temp[0])) # => no. of columns in each row = embedding vector size


not_hate_space = torch.tensor(temp).to(device).requires_grad_()

print(not_hate_space.is_leaf)

# not_hate_space
# not_hate_space.requires_grad

True


In [14]:
# Trial matmul

t1 = torch.randn(11, 768)
t2 = torch.randn(4, 23, 768)

print(torch.transpose(t2, 1, 2).shape)

torch.matmul(t1, torch.transpose(t2, 1, 2)).shape

torch.Size([4, 768, 23])


torch.Size([4, 11, 23])

In [15]:
print("hate_space.grad:", hate_space.grad)
print("not_hate_space.grad:", not_hate_space.grad)

hate_space.grad: None
not_hate_space.grad: None


In [16]:
class Custom_Dataset(torch.utils.data.Dataset):
    
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels
        
    def __getitem__(self, index: int) -> (torch.Tensor, int): # => (X, y)
        
        X = self.data[index]
        y = self.labels[index]

        return (X, y)
    
    
    def __len__(self) -> int:
        
        return len(self.data)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(tweets, list(df.classk), test_size=0.2, shuffle=True)

print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

19826 19826
4957 4957


In [18]:
train_data = Custom_Dataset(data=X_train, labels=y_train)
test_data = Custom_Dataset(data=X_test, labels=y_test)

train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=3, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_data, batch_size=1, shuffle=False)


In [19]:
import random
l=[[random.uniform(-1,1)] for i in range(11)]
l

[[0.06176514685879941],
 [-0.40084984457482054],
 [0.26412144710318675],
 [-0.6917484275709831],
 [0.5974571457818376],
 [0.720798398253341],
 [0.9612115637060441],
 [-0.15719566205866453],
 [-0.004461952363612021],
 [0.1188575859393779],
 [-0.04800085341699334]]

In [20]:
# next(iter(test_loader)) 
tensor_shape = (11,1)
hate_space_weights = torch.tensor(l).to(device).requires_grad_()
not_hate_space_weights = torch.tensor(l).to(device).requires_grad_()

print(hate_space_weights.device,not_hate_space_weights.is_leaf)

cuda:0 True


In [21]:
hate_space_weights.is_leaf

True

In [22]:
import torch.nn.functional as F

class Model0(nn.Module):

    def __init__(self, model, tokenizer):
        super().__init__()
        self.tokenizer = tokenizer
        self.model = model

    def forward(self, X):
        inputs = self.tokenizer(X, return_tensors="pt").to(device)
        outputs = self.model(**inputs)
        outputs = outputs.last_hidden_state.mean(1).transpose(0, 1)

        col_norms = torch.norm(outputs, p=2, dim=0, keepdim=True)
        outputs = outputs / col_norms
        
        Psk_hate = torch.matmul(torch.matmul(hate_space/torch.norm(hate_space,p=2, dim=0, keepdim=True),outputs).transpose(0, 1), hate_space_weights)
        Psk_not_hate = torch.matmul(torch.matmul(not_hate_space/torch.norm(not_hate_space,p=2, dim=0, keepdim=True),outputs).transpose(0, 1), not_hate_space_weights)

        # Construct the output tensor with requires_grad=True (assuming Psk_hate and Psk_not_hate have gradients)
        output_tensor = torch.cat((Psk_hate, Psk_not_hate), dim=0).requires_grad_()

        return output_tensor


In [23]:
model0 = Model0(model, tokenizer)

# X, y = next(iter(train_loader))
# Psk_hate, Psk_not_hate = model0(X)

# Semi-SSM

In [24]:
def L_inter(spaces):
    
    means = [torch.mean(spaces[i]) for i in range(spaces.shape[0])]
    
    loss = torch.tensor(0.0, requires_grad=True)
    
    for k in range(len(means)):
        cur = torch.tensor(0.0, requires_grad=True)
        for l in range(len(means)):
            if l == k:
                continue
            cur = cur + (1 / (1 - ((means[k] * means[l]))))
        
        loss = loss + cur
    
    return loss
            
            

def L_intra(spaces):
    loss=torch.tensor(0.0, requires_grad=True)
    for k in range(len(spaces)):
        loss=loss+1/torch.var(spaces[k], dim=0)
    
    return torch.sum(loss)/loss.shape[0]




In [25]:
L_inter(torch.concat((torch.tensor([[0.33, 0.54, 0.37], [0.72, 0.74, 0.31], [0.61, 0.26, 0.56]], dtype=torch.float32), 
       torch.tensor([[0.22, 0.32, 0.15], [0.12, -0.08, 0.45], [0.14, 0.28, -0.11]], dtype=torch.float32))))

tensor(33.6994, grad_fn=<AddBackward0>)

In [26]:
# temp = torch.tensor(10.3, requires_grad=True)

# temp

In [27]:
# res = [temp, temp]

# loss = 0

# loss += res[0] * res[1]

# loss

In [28]:
print(hate_space,not_hate_space)

tensor([[-0.0310,  0.1629,  0.0097,  ..., -0.0019,  0.0305, -0.0738],
        [-0.0411,  0.0255, -0.0069,  ..., -0.3014, -0.0704, -0.0058],
        [ 0.0085,  0.0397,  0.0388,  ..., -0.1430,  0.0385,  0.0430],
        ...,
        [-0.1312, -0.0045, -0.0484,  ..., -0.2071, -0.0556, -0.0245],
        [-0.0346,  0.1688,  0.0396,  ..., -0.2303, -0.1220,  0.0037],
        [-0.0049,  0.0358,  0.0281,  ..., -0.1855, -0.0979, -0.0800]],
       device='cuda:0', requires_grad=True) tensor([[-0.0039,  0.0822,  0.0470,  ..., -0.0254, -0.0671, -0.0814],
        [ 0.0216,  0.1387,  0.0708,  ..., -0.1220, -0.0591, -0.0006],
        [-0.1839,  0.1045,  0.1317,  ...,  0.1253, -0.0803,  0.0557],
        ...,
        [-0.0444,  0.0534,  0.0910,  ...,  0.1400,  0.0228, -0.0028],
        [-0.1128,  0.0228,  0.0920,  ...,  0.0764, -0.0988,  0.0147],
        [-0.0823,  0.0630,  0.0675,  ..., -0.0101, -0.0605,  0.0270]],
       device='cuda:0', requires_grad=True)


In [29]:
print(hate_space_weights,not_hate_space_weights)

tensor([[ 0.0618],
        [-0.4008],
        [ 0.2641],
        [-0.6917],
        [ 0.5975],
        [ 0.7208],
        [ 0.9612],
        [-0.1572],
        [-0.0045],
        [ 0.1189],
        [-0.0480]], device='cuda:0', requires_grad=True) tensor([[ 0.0618],
        [-0.4008],
        [ 0.2641],
        [-0.6917],
        [ 0.5975],
        [ 0.7208],
        [ 0.9612],
        [-0.1572],
        [-0.0045],
        [ 0.1189],
        [-0.0480]], device='cuda:0', requires_grad=True)


In [30]:
model0.to(device)
# hate_space = hate_space.to(device)
# not_hate_space = not_hate_space.to(device)
# hate_space_weights = hate_space_weights.to(device)
# not_hate_space_weights = not_hate_space_weights.to(device)
print(hate_space.is_leaf)
optimizer = torch.optim.Adam(params=[hate_space, not_hate_space, hate_space_weights, not_hate_space_weights], lr=0.01)
model0.train()
#criterion = nn.CrossEntropyLoss()
model0.train()
# with torch.inference_mode():
cur=0.1
prev=0
pprev=0
for _ in range(3) :
    for i, batch in enumerate(train_loader):
#         if i == 1:
#             break
        if i % 2000 == 0:
            print(i)

        x, Y = batch
        loss = 0

        for X, y in zip(x, Y):
            y_preds = model0(X)
#             print(y_preds)

            # Use long instead of float for target labels
            #print(hate_space.requires_grad)
#             print(y)
#             target = torch.tensor([y,1-y]).long().to(device)
# #             print(target)
#             loss += F.binary_cross_entropy_with_logits(y_preds.squeeze(), target.float())
            loss+=F.cross_entropy(y_preds.view(1, -1).to(device), torch.tensor([y]).to(device))
            #loss=torch.sum(y_preds)
#             print(loss)
        loss /= len(x)
        loss += 0.7*L_inter(torch.cat((hate_space, not_hate_space))) + 0.5*L_intra(torch.stack([hate_space, not_hate_space]))
            
        optimizer.zero_grad()
#         print("Before backward pass:")
#         print("hate_space.grad:", hate_space.grad)
#         print("not_hate_space.grad:", not_hate_space.grad)
        loss.backward()
        optimizer.step()
#         print("\nAfter backward pass:")
#         print("hate_space.grad:", hate_space.grad)
#         print("not_hate_space.grad:", not_hate_space.grad)
#         print(not_hate_space_weights.grad)
    correct = 0
    total = 1000

    true = []
    preds = []

    with torch.inference_mode():
        for i, batch in enumerate(test_loader):
            if i // 1000 == 1:
                break
            X, y = batch
            Psk_hate, Psk_not_hate = model0(X)

            y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

            true.extend(y)
            preds.append(y_predict)

            curr = torch.eq(y_predict, y)

            correct += torch.sum(curr)

    print(f"Test Accuracy: {correct/total}")
    pprev=prev
    prev=cur
    cur=correct/total
    print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / total}")  




True
0
2000
4000
6000
Test Accuracy: 0.8610000014305115
Test Accuracy: 0.8610000014305115
0
2000
4000
6000
Test Accuracy: 0.8690000176429749
Test Accuracy: 0.8690000176429749
0
2000
4000
6000
Test Accuracy: 0.8709999918937683
Test Accuracy: 0.8709999918937683


In [31]:
print(hate_space_weights,not_hate_space_weights)

tensor([[-4.3291],
        [-4.9192],
        [-0.4532],
        [-4.0089],
        [ 2.7345],
        [ 2.8786],
        [ 3.4790],
        [ 2.2470],
        [ 2.0515],
        [-0.4445],
        [ 1.4017]], device='cuda:0', requires_grad=True) tensor([[-0.6584],
        [-1.8843],
        [ 0.7324],
        [-0.8476],
        [ 1.6107],
        [ 2.2955],
        [ 2.9282],
        [-0.9179],
        [-0.1725],
        [-0.2973],
        [ 0.2375]], device='cuda:0', requires_grad=True)


In [32]:
print(hate_space,not_hate_space)

tensor([[-14.8571,   5.2225,  -0.2380,  ...,  11.3617,   1.0863,  -0.1735],
        [ -1.1379,   3.6035,   0.1324,  ...,   2.9925,   0.6323,   2.7377],
        [  3.1501,  -6.1537,  -1.3318,  ...,  -5.9957,   3.2171,   2.9819],
        ...,
        [ -0.7729,  -4.6986,  -1.0272,  ...,  -6.1508, -11.3660,   6.1742],
        [ -6.6332,   4.6960,  -1.9656,  ...,   1.7463,   1.2318,   3.7703],
        [  6.4563, -10.2264,  15.4512,  ...,  -4.7571,   0.3598,  -1.7879]],
       device='cuda:0', requires_grad=True) tensor([[ 0.4311,  1.2980, -0.2501,  ..., -1.7160, -0.1799, -0.3113],
        [ 0.1211, -1.0474, -0.5386,  ..., -1.5608, -0.3713, -2.8873],
        [-0.2818,  1.7578,  0.6980,  ...,  1.4894, -0.3308,  1.0140],
        ...,
        [ 3.5021, -1.1518, -0.7376,  ...,  0.5796,  0.5234, -1.0280],
        [-0.6200, -0.8037, -0.9822,  ...,  0.5753, -0.1958,  2.8440],
        [-1.0501, -0.7786, -0.0553,  ...,  0.0565, -0.3642,  1.7385]],
       device='cuda:0', requires_grad=True)


In [33]:
torch.concat((hate_space, not_hate_space)).shape

torch.Size([22, 768])

In [34]:
correct = 0
total = len(y_test)

true = []
preds = []

with torch.inference_mode():
    for i, batch in enumerate(test_loader):
        if i < 1000 == 0:
            continue
        X, y = batch
        Psk_hate, Psk_not_hate = model0(X)

        y_predict = torch.argmax(torch.tensor([Psk_hate.mean().item(), Psk_not_hate.mean().item()]))

        true.extend(y)
        preds.append(y_predict)

        cur = torch.eq(y_predict, y)

        correct += torch.sum(cur)

print(f"Test Accuracy: {correct/3000}")
print(f"Test Accuracy: {torch.sum(torch.eq(torch.tensor(true), torch.tensor(preds))) / 3000}")       

Test Accuracy: 1.4600000381469727
Test Accuracy: 1.4600000381469727


In [35]:
from sklearn.metrics import precision_score, recall_score

print(precision_score(y_test, preds, average='macro'))
print(recall_score(y_test, preds, average='macro'))

0.8056579356161017
0.7336288013534564
